# Generated by Django 5.2.5 on 2025-08-10 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='FoundingMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('president', 'President'), ('vice_president', 'Vice President'), ('director_marketing', 'Director, Marketing'), ('director_projects', 'Director, Projects'), ('other', 'Other')], max_length=100)),
                ('current_level_of_study', models.CharField(choices=[('ug_1', 'Undergraduate - First Year'), ('ug_2', 'Undergraduate - Second Year'), ('ug_3', 'Undergraduate - Third Year'), ('ug_4', 'Undergraduate - Fourth Year'), ('pg_masters', 'Postgraduate - Masters'), ('pg_doctoral', 'Postgraduate - Doctoral'), ('other', 'Other')], max_length=100)),
                ('discipline', models.CharField(max_length=100)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('proof_of_association', models.FileField(blank=True, null=True, upload_to='proofs/')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='founding_member', to='smile_forms.contact')),
            ],
        ),
        migrations.CreateModel(
            name='PointOfContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point_of_contact', to='smile_forms.contact')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founding_members', models.ManyToManyField(related_name='university_chapters', to='smile_forms.foundingmember')),
                ('point_of_contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smile_forms.pointofcontact')),
                ('university', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smile_forms.university')),
            ],
        ),
    ]
